__version__ = '0.1.4'
__author__ = 'Zhang Huangbin'
__author_mail__ = 'zhb@iredmail.org'
__url_iredadmin_ldap_latest__ = 'http://iredmail.org/version/check.py/ose.xml'
__url_iredadmin_mysql_latest__ = 'http://iredmail.org/version/check.py/ose.xml'
